{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "c9b6bae2_c634a1c3",
        "filename": "src/Utils.cpp",
        "patchSetId": 1
      },
      "lineNbr": 171,
      "author": {
        "id": 1000153
      },
      "writtenOn": "2022-08-18T14:14:24Z",
      "side": 0,
      "message": "Do we want to keep this print statement in the catch block?",
      "range": {
        "startLine": 171,
        "startChar": 0,
        "endLine": 171,
        "endChar": 67
      },
      "revId": "6c106d66e390352a6914e8dc5ddad20943eceaa6",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "790088f8_7493ea4e",
        "filename": "src/Utils.cpp",
        "patchSetId": 1
      },
      "lineNbr": 171,
      "author": {
        "id": 1000733
      },
      "writtenOn": "2022-08-18T18:18:02Z",
      "side": 0,
      "message": "I looked at that, but considering it\u0027s unconditionally preceded by\n\n```\n            std::cerr \u003c\u003c \"While calling GetManagedObjects on service:\"\n                      \u003c\u003c entityManagerName \u003c\u003c \" exception name:\" \u003c\u003c e.name()\n                      \u003c\u003c \"and description:\" \u003c\u003c e.description()\n                      \u003c\u003c \" was thrown\\n\";\n```\n\nwhich already mentions entity-manager and provides more detail to boot, I figured it was pretty much entirely redundant.",
      "parentUuid": "c9b6bae2_c634a1c3",
      "range": {
        "startLine": 171,
        "startChar": 0,
        "endLine": 171,
        "endChar": 67
      },
      "revId": "6c106d66e390352a6914e8dc5ddad20943eceaa6",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}